<?php

namespace Database\Seeders;

use App\Models\Seat;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SeatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seat::create([
        //     'seat_code'=>'a1',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);

        // Seat::create([
        //     'seat_code'=>'a2',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a3',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a4',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a5',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a6',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a7',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a8',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a8',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a9',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a10',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a11',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a12',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a13',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a14',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a15',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a16',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a17',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a18',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a19',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a20',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a21',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a22',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a23',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a24',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a25',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a26',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a27',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a28',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a29',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a30',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a31',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a32',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a33',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a34',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a35',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a36',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a37',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a38',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a39',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a40',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a41',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a42',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a43',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a45',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a46',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a47',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a48',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a49',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a50',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a51',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a52',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a53',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a54',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a55',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a56',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a57',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);

        // Seat::create([
        //     'seat_code'=>'a58',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a59',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a60',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a61',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a62',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a63',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a64',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a65',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a66',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a67',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);

        // Seat::create([
        //     'seat_code'=>'a68',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a69',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);
        // Seat::create([
        //     'seat_code'=>'a70',
        //     'is_booked'=>false,
        //     'seat_cost'=>'20',
        // ]);

        $seats = [];
        for ($i = 1; $i <= 70; $i++) {
            $seats[] = [
                'seat_code' => 'a' . $i,
                'is_booked' =>false,
                'seat_cost' =>20,
            ];
        }

        // Insert seats into the database
        Seat::insert($seats);


    }
}
